// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UniHub.Infrastructure.Data;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924231603_AdicionarInfoVendedor")]
    partial class AdicionarInfoVendedor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RestricaoAlimentarUsuario", b =>
                {
                    b.Property<Guid>("RestricoesAlimentaresId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuariosId")
                        .HasColumnType("uuid");

                    b.HasKey("RestricoesAlimentaresId", "UsuariosId");

                    b.HasIndex("UsuariosId");

                    b.ToTable("UsuarioRestricaoAlimentar", (string)null);
                });

            modelBuilder.Entity("UniHub.Domain.Entities.Correspondencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AceitaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IdentidadeRevelada")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("IdentidadeReveladaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SolicitacaoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("VoluntarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SolicitacaoId");

                    b.HasIndex("VoluntarioId");

                    b.ToTable("Correspondencia");
                });

            modelBuilder.Entity("UniHub.Domain.Entities.Doacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EntregueEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SolicitacaoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("VoluntarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SolicitacaoId");

                    b.HasIndex("VoluntarioId");

                    b.ToTable("Doacao");
                });

            modelBuilder.Entity("UniHub.Domain.Entities.HorarioVenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("HoraFim")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<Guid>("VendedorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VendedorId");

                    b.ToTable("HorariosVenda");
                });

            modelBuilder.Entity("UniHub.Domain.Entities.ItemPedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PrecoUnitarioNaCompra")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItemPedido");
                });

            modelBuilder.Entity("UniHub.Domain.Entities.LocalVenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Campus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PontoDeEncontro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VendedorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VendedorId");

                    b.ToTable("LocaisVenda");
                });

            modelBuilder.Entity("UniHub.Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompradorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompradorId");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("UniHub.Domain.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric");

                    b.Property<int>("QuantidadeDisponivel")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("VendedorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VendedorId");

                    b.ToTable("Produtos");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Produto");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("UniHub.Domain.Entities.RestricaoAlimentar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RestricoesAlimentares");
                });

            modelBuilder.Entity("UniHub.Domain.Entities.SolicitacaoApoio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoPublico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SolicitanteId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("SolicitacaoApoio");
                });

            modelBuilder.Entity("UniHub.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailInstitucional")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FotoPerfilUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("UniHub.Domain.Entities.Vendedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CardapioUrl")
                        .HasColumnType("text");

                    b.Property<string>("DescricaoNegocio")
                        .HasColumnType("text");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<decimal>("NotaMedia")
                        .HasColumnType("numeric");

                    b.Property<int>("QtdAvaliacoes")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Vendedores");
                });

            modelBuilder.Entity("UniHub.Domain.Entities.Voluntario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("AreasDeAtuacao")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("CodigoPublico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Voluntario");
                });

            modelBuilder.Entity("UniHub.Domain.Entities.ItemBazar", b =>
                {
                    b.HasBaseType("UniHub.Domain.Entities.Produto");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Condicao")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("ItemBazar");
                });

            modelBuilder.Entity("RestricaoAlimentarUsuario", b =>
                {
                    b.HasOne("UniHub.Domain.Entities.RestricaoAlimentar", null)
                        .WithMany()
                        .HasForeignKey("RestricoesAlimentaresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniHub.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UniHub.Domain.Entities.Correspondencia", b =>
                {
                    b.HasOne("UniHub.Domain.Entities.SolicitacaoApoio", "Solicitacao")
                        .WithMany("Correspondencias")
                        .HasForeignKey("SolicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniHub.Domain.Entities.Voluntario", "Voluntario")
                        .WithMany("Correspondencias")
                        .HasForeignKey("VoluntarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitacao");

                    b.Navigation("Voluntario");
                });

            modelBuilder.Entity("UniHub.Domain.Entities.Doacao", b =>
                {
                    b.HasOne("UniHub.Domain.Entities.SolicitacaoApoio", "Solicitacao")
                        .WithMany("Doacoes")
                        .HasForeignKey("SolicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniHub.Domain.Entities.Voluntario", "Voluntario")
                        .WithMany()
                        .HasForeignKey("VoluntarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitacao");

                    b.Navigation("Voluntario");
                });

            modelBuilder.Entity("UniHub.Domain.Entities.HorarioVenda", b =>
                {
                    b.HasOne("UniHub.Domain.Entities.Vendedor", "Vendedor")
                        .WithMany("Horarios")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("UniHub.Domain.Entities.ItemPedido", b =>
                {
                    b.HasOne("UniHub.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniHub.Domain.Entities.Produto", "Produto")
                        .WithMany("ItensPedido")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("UniHub.Domain.Entities.LocalVenda", b =>
                {
                    b.HasOne("UniHub.Domain.Entities.Vendedor", "Vendedor")
                        .WithMany("Locais")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("UniHub.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("UniHub.Domain.Entities.Usuario", "Comprador")
                        .WithMany("Pedidos")
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comprador");
                });

            modelBuilder.Entity("UniHub.Domain.Entities.Produto", b =>
                {
                    b.HasOne("UniHub.Domain.Entities.Vendedor", "Vendedor")
                        .WithMany("ProdutosPublicados")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("UniHub.Domain.Entities.SolicitacaoApoio", b =>
                {
                    b.HasOne("UniHub.Domain.Entities.Usuario", "Solicitante")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("UniHub.Domain.Entities.Vendedor", b =>
                {
                    b.HasOne("UniHub.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Vendedor")
                        .HasForeignKey("UniHub.Domain.Entities.Vendedor", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("UniHub.Domain.Entities.Voluntario", b =>
                {
                    b.HasOne("UniHub.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Voluntario")
                        .HasForeignKey("UniHub.Domain.Entities.Voluntario", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("UniHub.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("UniHub.Domain.Entities.Produto", b =>
                {
                    b.Navigation("ItensPedido");
                });

            modelBuilder.Entity("UniHub.Domain.Entities.SolicitacaoApoio", b =>
                {
                    b.Navigation("Correspondencias");

                    b.Navigation("Doacoes");
                });

            modelBuilder.Entity("UniHub.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Pedidos");

                    b.Navigation("Solicitacoes");

                    b.Navigation("Vendedor");

                    b.Navigation("Voluntario");
                });

            modelBuilder.Entity("UniHub.Domain.Entities.Vendedor", b =>
                {
                    b.Navigation("Horarios");

                    b.Navigation("Locais");

                    b.Navigation("ProdutosPublicados");
                });

            modelBuilder.Entity("UniHub.Domain.Entities.Voluntario", b =>
                {
                    b.Navigation("Correspondencias");
                });
#pragma warning restore 612, 618
        }
    }
}
